Repository canonical/postgresql-operator, pull requests merged in 2025-02, with the labels that each got.

#611 [DPE-3684][DPE-6020] Reinitialise raft
  actions.yaml
  poetry.lock
  pyproject.toml
  src/charm.py
  src/cluster.py
  src/relations/async_replication.py
  tests/integration/ha_tests/test_scaling.py
  tests/integration/ha_tests/test_scaling_three_units.py
  tests/integration/test_charm.py
  tests/unit/test_charm.py
  tests/unit/test_cluster.py
Labels: Libraries: Out of sync

#749 [MISC] Define charm utility properties
  src/backups.py
  src/charm.py
  src/relations/async_replication.py
  src/relations/db.py
  src/relations/postgresql_provider.py
Labels: Libraries: Out of sync

#759 [DPE-6020] Better promote-to-primary unit scope error handling
  lib/charms/data_platform_libs/v0/data_interfaces.py
  lib/charms/data_platform_libs/v0/data_models.py
  lib/charms/grafana_agent/v0/cos_agent.py
  lib/charms/operator_libs_linux/v2/snap.py
  lib/charms/postgresql_k8s/v0/postgresql.py
  lib/charms/tempo_coordinator_k8s/v0/charm_tracing.py
  poetry.lock
  pyproject.toml
  src/charm.py
  src/cluster.py
  tests/integration/ha_tests/test_async_replication.py
  tests/unit/test_charm.py
  tests/unit/test_cluster.py
Labels: Libraries: OK

#767 [MISC] Disable Nextcloud test
  tests/integration/new_relations/test_new_relations_2.py
Labels: Libraries: Out of sync

#727 [DPE-6323] Handle missing stanza output
  lib/charms/tempo_coordinator_k8s/v0/charm_tracing.py
  src/backups.py
  tests/unit/test_backups.py
  tests/unit/test_charm.py
Labels: bug, Libraries: OK

#774 [MISC] Define charm constants
  lib/charms/postgresql_k8s/v0/postgresql.py
  src/charm.py
  src/constants.py
  tests/integration/helpers.py
  tests/integration/new_relations/test_new_relations_1.py
  tests/integration/new_relations/test_relations_coherence.py
Labels: Libraries: Out of sync, not bug or enhancement
