Repository canonical/postgresql-operator, pull requests merged in 2025-06, with the labels that each got.

#909 [DPE-7309][DPE-7326] Switch to TLSv4
  actions.yaml
  lib/charms/postgresql_k8s/v0/postgresql.py
  lib/charms/postgresql_k8s/v0/postgresql_tls.py
  lib/charms/tempo_coordinator_k8s/v0/charm_tracing.py
  lib/charms/tls_certificates_interface/v2/tls_certificates.py
  lib/charms/tls_certificates_interface/v4/tls_certificates.py
  metadata.yaml
  src/backups.py
  src/charm.py
  src/cluster.py
  src/constants.py
  src/relations/postgresql_provider.py
  src/relations/tls.py
  src/relations/tls_transfer.py
  templates/patroni.yml.j2
  templates/pgbackrest.conf.j2
  tests/integration/ha_tests/helpers.py
  tests/integration/ha_tests/test_async_replication.py
  tests/integration/helpers.py
  tests/integration/test_backups_aws.py
  tests/integration/test_backups_pitr_aws.py
  tests/integration/test_backups_pitr_gcp.py
  tests/integration/test_charm.py
  tests/integration/test_tls.py
  tests/spread/test_upgrade.py/task.yaml
  tests/spread/test_upgrade_from_stable.py/task.yaml
  tests/unit/test_backups.py
  tests/unit/test_charm.py
  tests/unit/test_cluster.py
  tests/unit/test_tls.py
  tests/unit/test_tls_transfer.py
Labels: enhancement, Libraries: Out of sync

#933 [MISC] Remove JujuVersion warning in 14/edge
  lib/charms/operator_libs_linux/v2/snap.py
  lib/charms/tempo_coordinator_k8s/v0/charm_tracing.py
  lib/charms/tls_certificates_interface/v2/tls_certificates.py
  src/charm.py
  tests/unit/conftest.py
  tests/unit/test_charm.py
Labels: Libraries: OK, not bug or enhancement

#934 [DPE-7309][DPE-7326] Re-enable upgrade tests
  lib/charms/operator_libs_linux/v2/snap.py
  poetry.lock
  pyproject.toml
  src/backups.py
  tests/integration/ha_tests/test_self_healing_3.py
  tests/integration/ha_tests/test_smoke.py
  tests/spread/test_upgrade.py/task.yaml
  tests/spread/test_upgrade_from_stable.py/task.yaml
Labels: Libraries: OK, not bug or enhancement

#932 [DPE-7498] Create DBA role
  lib/charms/postgresql_k8s/v1/postgresql.py
  templates/patroni.yml.j2
  tests/integration/helpers.py
  tests/integration/test_predefined_dba_role.py
  tests/integration/test_predefined_roles.py
  tests/spread/test_predefined_dba_role.py/task.yaml
Labels: enhancement, Libraries: Out of sync

#921 [DPE-7500] Create catalog/database level roles
  lib/charms/postgresql_k8s/v1/postgresql.py
  src/charm.py
  src/relations/postgresql_provider.py
  templates/patroni.yml.j2
  tests/integration/helpers.py
  tests/integration/new_relations/test_new_relations_1.py
  tests/integration/test_predefined_catalog_roles.py
  tests/integration/test_predefined_dba_role.py
  tests/integration/test_predefined_roles.py
  tests/spread/test_predefined_catalog_roles.py/task.yaml
  tests/unit/test_postgresql_provider.py
Labels: Libraries: Out of sync

#944 [DPE-7502] Update PG to 16.9
  refresh_versions.toml
Labels: not bug or enhancement

#943 [DPE-7502] Update PG to 14.18
  src/constants.py
Labels: enhancement, Libraries: OK

#955 [DPE-7502] Improve upgrade tests to support both (in)compatible scenarios
  tests/integration/ha_tests/test_upgrade.py
  tests/integration/ha_tests/test_upgrade_from_stable.py
Labels: not bug or enhancement

#963 [MISC] Backport #959 to 14/edge
  lib/charms/postgresql_k8s/v0/postgresql.py
  src/relations/postgresql_provider.py
  tests/integration/ha_tests/test_async_replication.py
  tests/integration/helpers.py
  tests/unit/test_postgresql_provider.py
Labels: Libraries: OK, not bug or enhancement

#960 Predefined roles compatibility
  .github/workflows/ci.yaml
  .gitignore
  README.md
  lib/charms/postgresql_k8s/v1/postgresql.py
  scripts/cluster_topology_observer.py
  src/charm.py
  src/cluster.py
  src/cluster_topology_observer.py
  src/relations/postgresql_provider.py
  templates/patroni.yml.j2
  terraform/main.tf
  terraform/variables.tf
  tests/integration/ha_tests/test_async_replication.py
  tests/integration/ha_tests/test_scaling_three_units.py
  tests/integration/ha_tests/test_scaling_three_units_async.py
  tests/integration/helpers.py
  tests/integration/spaces/test_spaced_database.py
  tests/integration/test_pg_hba.py
  tests/integration/test_predefined_catalog_roles.py
  tests/integration/test_predefined_roles.py
  tests/spread/test_pg_hba.py/task.yaml
  tests/unit/test_charm.py
  tests/unit/test_cluster.py
  tests/unit/test_cluster_topology_observer.py
  tests/unit/test_postgresql_provider.py
Labels: enhancement

#972 [MISC] Renovate team
  .github/renovate.json5
Labels: Libraries: Out of sync, not bug or enhancement

#971 [MISC] Renovate team
  .github/renovate.json5
Labels: not bug or enhancement

#975 [DPE-7556] Add catalog/database level roles and mark chamed_dba_role as done
  docs/explanation/roles.md
Labels: not bug or enhancement

#999 [DPE-7614] Remove replica reinitialisations
  src/charm.py
  tests/unit/test_charm.py
Labels: enhancement

#1002 [DPE-7627] Allow `charmed_dba` role members to connect to other databases
  templates/patroni.yml.j2
  tests/integration/test_predefined_dba_role.py
Labels: not bug or enhancement
