Repository canonical/postgresql-operator, pull requests merged in 2025-04, with the labels that each got.

#813 [MISC] Sync main to 16/edge
  .github/workflows/approve_renovate_pr.yaml
  .github/workflows/check_pr.yaml
  .github/workflows/ci.yaml
  .github/workflows/promote.yaml
  .github/workflows/release.yaml
  .github/workflows/sync_docs.yaml
  scripts/cluster_topology_observer.py
  src/charm.py
  src/cluster_topology_observer.py
  tests/integration/ha_tests/helpers.py
  tests/unit/test_charm.py
  tests/unit/test_cluster_topology_observer.py
Labels: Libraries: OK, not bug or enhancement

#814 Create pull_request_template.md
  .github/pull_request_template.md
Labels: not bug or enhancement

#822 Create SECURITY.md
  SECURITY.md
Labels: not bug or enhancement

#827 Update README file's security section
  README.md
Labels: documentation, not bug or enhancement

#812 [MISC] Conditional checksum calculation
  poetry.lock
  pyproject.toml
  src/backups.py
  tests/unit/test_backups.py
Labels: Libraries: OK, not bug or enhancement

#828 [DPE-6218] Static code analysis
  .github/workflows/tiobe_scan.yaml
Labels: Libraries: Out of sync, not bug or enhancement

#831 [MISC] Disable landscape subordinate test lxd
  concierge.yaml
  tests/integration/test_subordinates.py
Labels: Libraries: Out of sync, not bug or enhancement

#832 [MISC] Update snapped PostgreSQL
  src/constants.py
Labels: Libraries: Out of sync, not bug or enhancement

#823 [DPE-6345] LDAP I: Create access groups
  lib/charms/postgresql_k8s/v0/postgresql.py
  src/charm.py
  src/relations/db.py
  src/relations/postgresql_provider.py
  src/upgrade.py
  tests/unit/test_db.py
  tests/unit/test_postgresql_provider.py
Labels: enhancement, Libraries: Out of sync

#824 [DPE-6345] LDAP II: Include charm libs
  lib/charms/certificate_transfer_interface/v0/certificate_transfer.py
  lib/charms/glauth_k8s/v0/ldap.py
  lib/charms/postgresql_k8s/v0/postgresql_tls.py
  metadata.yaml
  pyproject.toml
  src/charm.py
  src/constants.py
  tests/integration/helpers.py
  tests/integration/test_backups_pitr_aws.py
  tests/integration/test_backups_pitr_gcp.py
  tests/integration/test_tls.py
  tests/unit/test_charm.py
Labels: enhancement, Libraries: Out of sync

#834 [MISC] Sync up changes from 14
  .github/pull_request_template.md
  .github/workflows/tiobe_scan.yaml
  README.md
  SECURITY.md
  config.yaml
  docs/explanation.md
  docs/explanation/e-architecture.md
  docs/explanation/e-users.md
  docs/how-to.md
  docs/how-to/h-deploy.md
  docs/how-to/h-enable-profiling.md
  docs/how-to/h-enable-tls.md
  docs/how-to/h-external-access.md
  docs/how-to/h-integrate.md
  docs/overview.md
  docs/reference.md
  docs/reference/r-contacts.md
  docs/reference/r-sos-report.md
  docs/tutorial/t-enable-tls.md
  docs/tutorial/t-set-up.md
  poetry.lock
  pyproject.toml
  src/backups.py
  src/charm.py
  src/config.py
  src/constants.py
  tests/integration/test_subordinates.py
  tests/unit/test_backups.py
Labels: Libraries: Out of sync, not bug or enhancement

#825 [DPE-6345] LDAP III: Define config and handlers
  config.yaml
  src/charm.py
  src/cluster.py
  src/config.py
  src/ldap.py
  templates/patroni.yml.j2
  tests/unit/test_charm.py
  tests/unit/test_cluster.py
  tests/unit/test_ldap.py
Labels: enhancement, Libraries: Out of sync

#838 [DPE-6345] LDAP IV: Define snap service
  src/charm.py
  src/utils.py
  tests/unit/test_charm.py
  tests/unit/test_utils.py
Labels: enhancement, Libraries: Out of sync

#845 [MISC] Disable network cut tests on arm
  tests/integration/ha_tests/test_self_healing.py
Labels: Libraries: Out of sync, not bug or enhancement

#849 [DPE-6345] LDAP V: Define mapping option
  config.yaml
  lib/charms/postgresql_k8s/v0/postgresql.py
  src/charm.py
  src/config.py
  tests/unit/test_charm.py
Labels: enhancement, Libraries: Out of sync

#840 [DPE-6815] disable pgaudit during extensions changes
  lib/charms/data_platform_libs/v0/data_interfaces.py
  lib/charms/postgresql_k8s/v0/postgresql.py
  tests/integration/test_plugins.py
Labels: bug, Libraries: OK

#844 [MISC] Disable network cut tests on arm
  tests/integration/ha_tests/test_self_healing.py
Labels: Libraries: Out of sync, not bug or enhancement

#842 [DPE-6815] disable pgaudit during extensions changes
  lib/charms/data_platform_libs/v0/data_interfaces.py
  lib/charms/postgresql_k8s/v0/postgresql.py
Labels: Libraries: OK, not bug or enhancement

#833 [DPE-6189] Manage passwords with user secrets
  actions.yaml
  config.yaml
  src/charm.py
  src/config.py
  src/constants.py
  tests/integration/ha_tests/conftest.py
  tests/integration/ha_tests/helpers.py
  tests/integration/ha_tests/test_async_replication.py
  tests/integration/ha_tests/test_replication.py
  tests/integration/ha_tests/test_restore_cluster.py
  tests/integration/ha_tests/test_self_healing.py
  tests/integration/helpers.py
  tests/integration/test_backups_aws.py
  tests/integration/test_backups_gcp.py
  tests/integration/test_backups_pitr_aws.py
  tests/integration/test_backups_pitr_gcp.py
  tests/integration/test_charm.py
  tests/integration/test_password_rotation.py
  tests/integration/test_plugins.py
  tests/integration/test_tls.py
  tests/unit/test_backups.py
  tests/unit/test_charm.py
Labels: enhancement, Libraries: Out of sync

#843 [MISC] Sync main to 16/edge
  concierge.yaml
  config.yaml
  lib/charms/certificate_transfer_interface/v0/certificate_transfer.py
  lib/charms/data_platform_libs/v0/data_interfaces.py
  lib/charms/glauth_k8s/v0/ldap.py
  lib/charms/postgresql_k8s/v0/postgresql_tls.py
  metadata.yaml
  poetry.lock
  pyproject.toml
  src/charm.py
  src/cluster.py
  src/config.py
  src/constants.py
  src/ldap.py
  src/relations/postgresql_provider.py
  src/rotate_logs.py
  src/upgrade.py
  src/utils.py
  templates/patroni.yml.j2
  tests/integration/helpers.py
  tests/integration/test_backups_pitr_aws.py
  tests/integration/test_backups_pitr_gcp.py
  tests/integration/test_tls.py
  tests/unit/test_charm.py
  tests/unit/test_cluster.py
  tests/unit/test_ldap.py
  tests/unit/test_postgresql_provider.py
  tests/unit/test_utils.py
Labels: Libraries: Out of sync, not bug or enhancement

#846 [DPE-6664] Make username mandatory in set-password
  src/charm.py
  tests/unit/test_charm.py
Labels: enhancement, Libraries: Out of sync

#853 Add conditional expose directive
  terraform/main.tf
  terraform/variables.tf
Labels: enhancement

#856 [MISC] No default scope for promote action
  actions.yaml
Labels: enhancement, Libraries: Out of sync

#855 [MISC] No default scope in promote action
  actions.yaml
Labels: enhancement, Libraries: Out of sync
