Repository canonical/postgresql-operator, pull requests merged in 2025-07, with the labels that each got.

#925 [MISC] Parallel patroni calls
  poetry.lock
  pyproject.toml
  scripts/cluster_topology_observer.py
  src/charm.py
  src/cluster.py
  tests/unit/test_charm.py
  tests/unit/test_cluster.py
  tests/unit/test_cluster_topology_observer.py
Labels: enhancement, Libraries: Out of sync

#1025 [DPE-7678] Enable disable extensions afrer restore
  lib/charms/data_platform_libs/v0/data_interfaces.py
  lib/charms/tempo_coordinator_k8s/v0/charm_tracing.py
  src/charm.py
  tests/unit/test_charm.py
Labels: bug

#1024 [DPE-7691] Bump snap revision to 197/198 to use _daemon_ (584792)
  docs/explanation/logs.md
  docs/how-to/switchover-failover.md
  docs/reference/troubleshooting/cli-helpers.md
  docs/reference/troubleshooting/index.md
  refresh_versions.toml
  scripts/cluster_topology_observer.py
  src/backups.py
  src/charm.py
  src/cluster.py
  src/relations/async_replication.py
  templates/patroni.yml.j2
  templates/pgbackrest.logrotate.j2
  tests/integration/test_tls.py
  tests/spread/test_upgrade.py/task.yaml
  tests/spread/test_upgrade_from_stable.py/task.yaml
  tests/unit/test_backups.py
  tests/unit/test_charm.py
  tests/unit/test_cluster.py
Labels: enhancement

#1003 [DPE-7628] Fix permissions for predefined roles
  lib/charms/postgresql_k8s/v1/postgresql.py
  src/relations/postgresql_provider.py
  templates/patroni.yml.j2
  tests/integration/conftest.py
  tests/integration/helpers.py
  tests/integration/jubilant_helpers.py
  tests/integration/new_relations/test_new_relations_1.py
  tests/integration/spaces/conftest.py
  tests/integration/test_audit.py
  tests/integration/test_invalid_database.py
  tests/integration/test_invalid_extra_user_roles.py
  tests/integration/test_predefined_catalog_roles.py
  tests/integration/test_predefined_dba_role.py
  tests/integration/test_predefined_roles.py
  tests/spread/test_invalid_database.py/task.yaml
  tests/spread/test_invalid_extra_user_roles.py/task.yaml
  tests/unit/test_postgresql_provider.py
Labels: not bug or enhancement

#1032 [MISC] Use test app beta for isolated test
  poetry.lock
  pyproject.toml
  tests/integration/spaces/test_spaced_database.py
  tests/spread/test_upgrade.py/task.yaml
Labels: bug

#1035 [DPE-7685] Docs PR for setpriv shim
  docs/explanation/architecture.md
  docs/how-to/switchover-failover.md
  docs/reference/troubleshooting/cli-helpers.md
Labels: documentation

#1006 Fix automatic doc checks
  docs/.custom_wordlist.txt
  docs/.sphinx/spellingcheck.yaml
  docs/conf.py
  docs/explanation/architecture.md
  docs/explanation/index.md
  docs/explanation/juju.md
  docs/explanation/legacy-charm.md
  docs/explanation/logs.md
  docs/explanation/security/cryptography.md
  docs/explanation/security/index.md
  docs/explanation/units.md
  docs/explanation/users.md
  docs/how-to/back-up-and-restore/configure-s3-radosgw.md
  docs/how-to/back-up-and-restore/index.md
  docs/how-to/back-up-and-restore/manage-backup-retention.md
  docs/how-to/cross-regional-async-replication/index.md
  docs/how-to/cross-regional-async-replication/integrate-with-a-client-app.md
  docs/how-to/cross-regional-async-replication/remove-or-recover-a-cluster.md
  docs/how-to/cross-regional-async-replication/set-up-clusters.md
  docs/how-to/deploy/air-gapped.md
  docs/how-to/deploy/aws-ec2.md
  docs/how-to/deploy/azure.md
  docs/how-to/deploy/gce.md
  docs/how-to/deploy/index.md
  docs/how-to/deploy/juju-storage.md
  docs/how-to/deploy/maas.md
  docs/how-to/deploy/sunbeam.md
  docs/how-to/deploy/terraform.md
  docs/how-to/deploy/tls-vip-access.md
  docs/how-to/development/index.md
  docs/how-to/development/integrate-with-your-charm.md
  docs/how-to/development/migrate-data-via-pg-dump.md
  docs/how-to/enable-ldap.md
  docs/how-to/enable-plugins-extensions/index.md
  docs/how-to/external-network-access.md
  docs/how-to/index.md
  docs/how-to/manage-passwords.md
  docs/how-to/monitoring-cos/enable-alert-rules.md
  docs/how-to/monitoring-cos/enable-monitoring.md
  docs/how-to/monitoring-cos/enable-profiling.md
  docs/how-to/monitoring-cos/enable-tracing.md
  docs/how-to/monitoring-cos/index.md
  docs/how-to/scale-replicas.md
  docs/how-to/switchover-failover.md
  docs/how-to/upgrade/index.md
  docs/how-to/upgrade/perform-a-minor-upgrade.md
  docs/index.md
  docs/reference/alert-rules.md
  docs/reference/contacts.md
  docs/reference/performance-and-resources.md
  docs/reference/releases.md
  docs/reference/statuses.md
  docs/reference/system-requirements.md
  docs/reference/troubleshooting/cli-helpers.md
  docs/reference/troubleshooting/index.md
  docs/reference/troubleshooting/sos-report.md
  docs/reference/versions.md
  docs/tutorial/index.md
Labels: documentation, not bug or enhancement

#1037 Bump PG slots max_replication_slots / max_wal_senders = 25
  src/charm.py
Labels: enhancement

#1036 [DPE-6259] pgbackrest config perms
  lib/charms/glauth_k8s/v0/ldap.py
  lib/charms/tls_certificates_interface/v4/tls_certificates.py
  src/backups.py
  tests/unit/test_backups.py
Labels: bug

#1041 [MISC] Remove psql setpriv shim and switch stable upgrade tests to 16/stable
  refresh_versions.toml
  tests/integration/ha_tests/test_upgrade.py
  tests/integration/ha_tests/test_upgrade_from_stable.py
  tests/integration/new_relations/test_new_relations_1.py
  tests/integration/new_relations/test_relations_coherence.py
Labels: enhancement

#1030 Reuse class PostgreSQL on each self.postgresql.* call
  src/charm.py
  src/cluster.py
Labels: enhancement

#1038 [DPE-6259] pgbackrest config perms
  lib/charms/data_platform_libs/v0/data_interfaces.py
  lib/charms/glauth_k8s/v0/ldap.py
  lib/charms/tempo_coordinator_k8s/v0/charm_tracing.py
  src/backups.py
  tests/integration/new_relations/test_new_relations_1.py
  tests/integration/new_relations/test_relations_coherence.py
  tests/unit/test_backups.py
Labels: bug, Libraries: Out of sync

#1054 [DPE-7792] Update predefined roles docs
  docs/.custom_wordlist.txt
  docs/explanation/roles.md
Labels: not bug or enhancement

#1040 (WIP) Major v16 tutorial edits
  docs/explanation/interfaces-and-endpoints.md
  docs/explanation/units.md
  docs/how-to/deploy/aws-ec2.md
  docs/how-to/deploy/azure.md
  docs/how-to/deploy/gce.md
  docs/how-to/deploy/juju-spaces.md
  docs/how-to/deploy/juju-storage.md
  docs/how-to/deploy/maas.md
  docs/how-to/deploy/multi-az.md
  docs/how-to/deploy/sunbeam.md
  docs/how-to/deploy/terraform.md
  docs/how-to/deploy/tls-vip-access.md
  docs/how-to/enable-ldap.md
  docs/how-to/enable-plugins-extensions/enable-timescaledb.md
  docs/how-to/manage-passwords.md
  docs/how-to/scale-replicas.md
  docs/index.md
  docs/reference/alert-rules.md
  docs/reference/versions.md
  docs/tutorial/index.md
Labels: bug, documentation

#1063 Fix MicroStack links
  docs/how-to/deploy/sunbeam.md
Labels: documentation, not bug or enhancement
