Repository canonical/postgresql-operator, pull requests merged in 2025-03, with the labels that each got.

#782 [MISC] Sanitize PostgreSQL extra-user-roles arg
  lib/charms/postgresql_k8s/v0/postgresql.py
  src/charm.py
  src/relations/postgresql_provider.py
  tests/unit/test_postgresql_provider.py
Labels: Libraries: Out of sync, not bug or enhancement

#786 [MISC] Fix PostgreSQL lib function signature
  lib/charms/postgresql_k8s/v0/postgresql.py
Labels: Libraries: Out of sync, not bug or enhancement

#787 Reduce required approvals on Renovate pull requests by 1
  .github/workflows/approve_renovate_pr.yaml
Labels: Libraries: Out of sync, not bug or enhancement

#791 [MISC] Update snapped Postgresql to 14.17
  src/constants.py
Labels: enhancement, Libraries: OK

#783 [DPE-6555] Add read only URIs
  lib/charms/data_platform_libs/v0/data_interfaces.py
  src/relations/postgresql_provider.py
  tests/integration/ha_tests/helpers.py
  tests/integration/new_relations/helpers.py
  tests/integration/new_relations/test_new_relations_1.py
  tests/integration/test_backups_aws.py
  tests/integration/test_backups_ceph.py
  tests/integration/test_backups_gcp.py
  tests/integration/test_backups_pitr_aws.py
  tests/integration/test_backups_pitr_gcp.py
  tests/integration/test_tls.py
  tests/unit/test_postgresql_provider.py
Labels: enhancement, Libraries: OK

#778 [DPE-6678] PostgreSQL Config Improvement
  config.yaml
  lib/charms/postgresql_k8s/v0/postgresql.py
  src/charm.py
  src/config.py
  templates/patroni.yml.j2
  tests/integration/test_config.py
Labels: enhancement

#804 [MISC] Use latest/stable lxd
  concierge.yaml
Labels: Libraries: OK, not bug or enhancement

#800 [DPE-6112] Sync main
  .github/workflows/approve_renovate_pr.yaml
  .github/workflows/check_pr.yaml
  .github/workflows/ci.yaml
  .github/workflows/promote.yaml
  .github/workflows/release.yaml
  .github/workflows/sync_docs.yaml
  charmcraft.yaml
  concierge.yaml
  config.yaml
  lib/charms/data_platform_libs/v0/data_interfaces.py
  lib/charms/postgresql_k8s/v0/postgresql.py
  src/charm.py
  src/config.py
  src/relations/postgresql_provider.py
  templates/patroni.yml.j2
  tests/integration/ha_tests/test_upgrade_from_stable.py
  tests/integration/new_relations/helpers.py
  tests/integration/new_relations/test_new_relations_1.py
  tests/integration/test_backups_aws.py
  tests/integration/test_backups_ceph.py
  tests/integration/test_backups_gcp.py
  tests/integration/test_backups_pitr_aws.py
  tests/integration/test_backups_pitr_gcp.py
  tests/integration/test_config.py
  tests/integration/test_tls.py
  tests/unit/test_postgresql_provider.py
Labels: Libraries: OK, not bug or enhancement
