Repository canonical/postgresql-operator, pull requests merged in 2025-10, with the labels that each got.

#1198 DPE-8470 Bump patroni from 3.2.2 to 3.3.8
  refresh_versions.toml
Labels: enhancement, Libraries: Out of sync

#1197 DPE-8470 Bump snap for Patroni to 3.3.8
  src/constants.py
Labels: enhancement, Libraries: OK

#1199 [MISC] Strict sync mode
  lib/charms/tls_certificates_interface/v4/tls_certificates.py
  src/cluster.py
  tests/integration/ha_tests/test_scaling.py
  tests/integration/ha_tests/test_scaling_three_units.py
  tests/integration/ha_tests/test_scaling_three_units_async.py
  tests/integration/ha_tests/test_self_healing_1.py
  tests/integration/ha_tests/test_self_healing_2.py
  tests/integration/ha_tests/test_self_healing_3.py
  tests/unit/test_cluster.py
Labels: enhancement, Libraries: OK

#1196 [MISC] Set strict sync mode
  src/cluster.py
  templates/patroni.yml.j2
  tests/integration/ha_tests/test_scaling.py
  tests/integration/ha_tests/test_scaling_three_units.py
  tests/integration/ha_tests/test_scaling_three_units_async.py
  tests/integration/ha_tests/test_self_healing.py
  tests/unit/test_cluster.py
Labels: enhancement, Libraries: OK

#1195 Remove old revision of secret
  src/charm.py
Labels: Libraries: OK, not bug or enhancement
