Repository canonical/postgresql-operator, pull requests merged in 2025-05, with the labels that each got.

#869 [DPE-6965] Wait for all storages to detatch in smoke test
  .github/workflows/integration_test.yaml
  tests/integration/ha_tests/test_smoke.py
Labels: Libraries: Out of sync, not bug or enhancement

#868 [MISC] Extend relation-user listing syntax
  lib/charms/postgresql_k8s/v0/postgresql.py
Labels: bug, Libraries: Out of sync

#880 [MISC] Split HA tests
  tests/integration/ha_tests/test_self_healing_1.py
  tests/integration/ha_tests/test_self_healing_2.py
  tests/integration/ha_tests/test_self_healing_3.py
  tests/spread/test_self_healing_1.py/task.yaml
  tests/spread/test_self_healing_2.py/task.yaml
  tests/spread/test_self_healing_3.py/task.yaml
Labels: Libraries: Out of sync, not bug or enhancement

#857 feat: [DPE-6904] Spaces support
  poetry.lock
  pyproject.toml
  src/charm.py
  src/cluster.py
  src/constants.py
  src/relations/async_replication.py
  src/relations/postgresql_provider.py
  src/utils.py
  templates/patroni.yml.j2
  tests/integration/new_relations/test_new_relations_1.py
  tests/integration/spaces/conftest.py
  tests/integration/spaces/test_spaced_database.py
  tests/spread/test_spaced_database.py/task.yaml
  tests/unit/test_charm.py
  tests/unit/test_cluster.py
  tests/unit/test_postgresql_provider.py
Labels: enhancement, Libraries: Out of sync

#889 Fix unit tests
  poetry.lock
  pyproject.toml
  tests/unit/conftest.py
Labels: Libraries: Out of sync, not bug or enhancement

#884 [MISC] Sync postgresql lib
  lib/charms/postgresql_k8s/v0/postgresql.py
  lib/charms/postgresql_k8s/v0/postgresql_tls.py
Labels: Libraries: Out of sync, not bug or enhancement

#912 [MISC] Delete runner password
  spread.yaml
Labels: Libraries: Out of sync, not bug or enhancement

#913 [MISC] Remove runner password
  spread.yaml
Labels: Libraries: Out of sync, not bug or enhancement

#900 [DPE-7129] Fix network cut without ip change test
  src/charm.py
  src/cluster.py
  tests/integration/ha_tests/helpers.py
  tests/unit/test_charm.py
Labels: Libraries: Out of sync, not bug or enhancement
