Repository canonical/postgresql-operator, pull requests merged in 2025-09, with the labels that each got.

#1127 [MISC] Update charm libs
  lib/charms/data_platform_libs/v0/data_interfaces.py
  lib/charms/data_platform_libs/v0/s3.py
  lib/charms/grafana_agent/v0/cos_agent.py
  lib/charms/operator_libs_linux/v2/snap.py
  lib/charms/tempo_coordinator_k8s/v0/charm_tracing.py
Labels: Libraries: OK, not bug or enhancement

#1129 [DPE-8063] Enable microceph test for arm64
  tests/integration/test_backups_ceph.py
  tests/spread/test_backups_ceph.py/task.yaml
Labels: Libraries: Out of sync, not bug or enhancement

#1126 [DPE-8062] Enable microceph test for arm64
  tests/integration/test_backups_ceph.py
  tests/spread/test_backups_ceph.py/task.yaml
Labels: not bug or enhancement

#1136 [MISC] Don't block if the snap cannot be installed
  src/charm.py
  tests/unit/test_charm.py
Labels: bug, Libraries: Out of sync

#1117 [DPE-8005] Handle empty region
  src/backups.py
  templates/pgbackrest.conf.j2
  tests/integration/conftest.py
  tests/integration/test_backups_ceph.py
  tests/unit/test_backups.py
Labels: bug

#1147 DPE-8296 Bump PostgreSQL to 14.19
  src/constants.py
Labels: enhancement, Libraries: Out of sync

#1158 Update versions and release documentation (14)
  docs/conf.py
  docs/explanation/charm-versions/index.md
  docs/explanation/charm-versions/legacy-charm.md
  docs/explanation/charm-versions/modern-charm.md
  docs/explanation/index.md
  docs/explanation/interfaces-and-endpoints.md
  docs/explanation/legacy-charm.md
  docs/explanation/security/index.md
  docs/how-to/deploy/juju-storage.md
  docs/how-to/deploy/tls-vip-access.md
  docs/how-to/development/integrate-with-your-charm.md
  docs/how-to/development/migrate-data-via-backup-restore.md
  docs/how-to/development/migrate-data-via-pg-dump.md
  docs/how-to/integrate-with-another-application.md
  docs/index.md
  docs/redirects.txt
  docs/reference/index.md
  docs/reference/releases.md
  docs/reference/statuses.md
  docs/reference/versions.md
Labels: documentation, enhancement

#1162 [DPE-8320] Fix backups with internal certificates
  lib/charms/tempo_coordinator_k8s/v0/charm_tracing.py
  src/charm.py
  src/relations/tls.py
  tests/integration/helpers.py
  tests/integration/test_backups_ceph.py
Labels: bug, Libraries: OK
