Repository canonical/postgresql-operator, pull requests merged in 2025-08, with the labels that each got.

#924 Logical Replication
  config.yaml
  lib/charms/postgresql_k8s/v1/postgresql.py
  metadata.yaml
  src/backups.py
  src/charm.py
  src/cluster.py
  src/config.py
  src/relations/logical_replication.py
  templates/patroni.yml.j2
  tests/integration/ha_tests/helpers.py
  tests/integration/ha_tests/test_logical_replication.py
  tests/spread/test_logical_replication.py/task.yaml
  tests/unit/test_charm.py
Labels: not bug or enhancement

#1072 [DPE-7594] Add custom users to pg_hba filter
  lib/charms/postgresql_k8s/v1/postgresql.py
  src/charm.py
  tests/unit/test_charm.py
Labels: not bug or enhancement

#1073 [DPE-7594] Add custom users to pg_hba filter
  src/charm.py
  tests/unit/test_charm.py
Labels: Libraries: Out of sync, not bug or enhancement

#1053 [MISC] Add Pyright to linting
  lib/charms/postgresql_k8s/v1/postgresql.py
  poetry.lock
  pyproject.toml
  src/backups.py
  src/charm.py
  src/cluster.py
  src/cluster_topology_observer.py
  src/config.py
  src/ldap.py
  src/locales.py
  src/relations/async_replication.py
  src/relations/logical_replication.py
  src/relations/postgresql_provider.py
  src/relations/tls.py
  src/rotate_logs.py
  tests/integration/ha_tests/test_scaling.py
  tests/integration/test_charm.py
  tests/unit/test_backups.py
  tests/unit/test_charm.py
  tests/unit/test_cluster.py
  tests/unit/test_tls.py
  tox.ini
Labels: not bug or enhancement

#1049 [DPE-7726] Use Patroni API for is_restart_pending() (instead of SQL select from pg_settings)
  .github/workflows/integration_test.yaml
  lib/charms/postgresql_k8s/v1/postgresql.py
  src/charm.py
  src/cluster.py
  src/relations/async_replication.py
  src/relations/postgresql_provider.py
  templates/patroni.yml.j2
  tests/integration/ha_tests/test_self_healing_3.py
  tests/unit/test_charm.py
  tests/unit/test_cluster.py
Labels: bug

#1118 Update charm-refresh to v3.1.0.2
  poetry.lock
  pyproject.toml
Labels: bug
